Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    SamMultipler:
        Description: "polarCloud Backend"
        Type: "String"
Resources:
    GetSAMPartyCount:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.js
            Runtime: nodejs10.x
            CodeUri: ./
            Environment:
                Variables:
                    SAM_MULTIPLIER: !Ref SamMultipler