AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ContactRouter
  
Globals:
  Function:
    Timeout: 3

Resources:
  ContactRouterLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: 
        Bucket: deployment-artifacts-backend
        Key: Backend.zip
      Handler: index.handler
      Runtime: nodejs10.x
      FunctionName: ContactRouter
